### ISSUE TITLE
Incorrect calculations for certain input

### ISSUE THREAD

**Issue by ThePharros** [LlemonDuck/dps-calculator#13]
The below input results in incorrect output:

**Input:**
![image](https://user-images.githubusercontent.com/18340303/124339815-f18f6180-db7e-11eb-8be5-23aeef7292dd.png)
![image](https://user-images.githubusercontent.com/18340303/124339803-e1778200-db7e-11eb-9db5-12211552c632.png)
![image](https://user-images.githubusercontent.com/18340303/124339823-04a23180-db7f-11eb-89e4-db91612b5ebf.png)
![image](https://user-images.githubusercontent.com/18340303/124339827-0b30a900-db7f-11eb-8079-af1e922c4533.png)

**Output:**
![image](https://user-images.githubusercontent.com/18340303/124339834-14217a80-db7f-11eb-89c3-10cd23a61470.png)

**Comment by ThePharros** [comment]
And these are the values I got in a custom DPS calculator for the above input:

![image](https://user-images.githubusercontent.com/18340303/124340037-59927780-db80-11eb-87ef-6364f6c4981c.png)

**Comment by LlemonDuck** [comment]
Crystal armour strength multiplier was being derived incorrectly from the attack bonus (was `2 * attBonus` instead of `2  * (attBonus - 1) + 1`, to double 30% => 60% instead of 130% => 260%).

Fixed in 277c415f. Will push out immediately as a quick fix.

We still had some discrepancies in our calculations, but I didn't see anything else that would be incorrect. Here are the new values I got:

![image](https://user-images.githubusercontent.com/1868974/124340262-ec7fe180-db81-11eb-90bf-7bde3cad50cb.png)

**Comment by ThePharros** [comment]
Ah that would do it lol, thanks for the quick fix. Yeah I'm not sure where the discrepancies arise. Seems like mine is calculating higher accuracy with lower damage by comparison. Would you mind sharing some behind the scenes calculations? Since the Max Hit gets calculated early we could start from there. calculation I'm getting:

**Effective Ranged Strength:**
ERS = ⌊(⌊(RangedLvl + Boost) * PrayBonus⌋ + AttStyle + 8) * VoidModifier⌋
       = ⌊(⌊(99 + 13) * 1.23⌋ + 0 + 8) * 1⌋
       = ⌊(⌊137.76⌋ + 8)⌋
       = ⌊137 + 8⌋
       = 145

**Max Hit:**
Gear Ranged Strength = 113
Gear Bonus = 1.275
Max = ⌊0.5 + (ERS * (GRS + 64) * GB) / 640⌋
        = ⌊0.5 + (145 * (113 + 64) * 1.275) / 640⌋
        = ⌊0.5 + (145 * (113 + 64) * 1.275) / 640⌋
        = ⌊0.5 + 32,722.85 / 640⌋
        = ⌊51.6294921875⌋
        = 51

Let me know if I made any mistakes.

**Comment by LlemonDuck** [comment]
Well I just realized I got strength and attack backwards so I have to push out another update 😞. Fixed in ac3c693b.

You do have the order a little off there: I apply the gear and crystal bonuses after the +320 /640, which matches the wiki page here:
https://oldschool.runescape.wiki/w/Damage_per_second/Ranged#Step_two:_Calculate_the_maximum_hit

The only part I'm not sure about is whether the two gear bonuses should be applied multiplicatively then rounded, or rounded separately. I wasn't able to find good resources on this aspect.

**Comment by ThePharros** [comment]
lol no worries.

and that order shouldn't matter as it's just associative property of multiplication; the calculation will come out the same.

According to the [ranged rebalance blog](https://secure.runescape.com/m=news/equipment-rebalance-ranged-meta-proposal?oldschool=1), the crystal armor and slayer helm bonuses stack together additively:
> For example, we expect using an imbued Slayer Helmet with the Crystal Body and Legs to be popular, as it’ll grant a total bonus of 40% Ranged accuracy and 27.5% Ranged damage while on any Slayer task.

In order of default, slayer helmet(i), crystal body, and crystal legs:
```
Gear Bonus Damage = (1 + 0.15 + 0.075 + 0.05) = 1.275
Gear Bonus Accuracy = (1 + 0.15 + 0.15 + 0.1) = 1.4
```
which matches the blog's values.

**Comment by LlemonDuck** [comment]
Closing for now, since the original crystal armour bonuses were resolved.

Residual changes needed for gear bonus additivity can be tracked in #17.
