### ISSUE TITLE
Ability to keep gear "in sync"

### ISSUE THREAD

**Issue by dominicfrost** [LlemonDuck/dps-calculator#20]
The "load equipment from client" feature is super handy. What would be even more handy would be if I could check a box ("keep synced" or something), that would keep your gear in sync while equipping different sets of items. 

I find myself comparing the max hit of different sets of gear quite frequently, and it's quite a few clicks to update my gear, go to the equipment tab, load new gear from the client, and then swap back to home to view the dps/max hit deltas.

**Comment by LlemonDuck** [comment]
Interesting, but I'm not sure I want to bring in a temporary band-aid solution for (what I hope to be) a short time until I finish the external, cleaned up calculation library. If it so happens that the library ends up delayed, I'll let you know and we can bring this in.

**Comment by LlemonDuck** [comment]
Especially now that the Load From Client button on the gear page will auto-detect combat stance/autocast spells/etc, it should be fairly quick to get an up-to-date calculation.

**Comment by Violet-Vibes** [comment]
Any progress on this? <3

**Comment by LlemonDuck** [comment]
I never ended up splitting off the calculations from the plugin and at this point I no longer think it's on the roadmap. @Cyborger1 are you interested in revisiting this? Perhaps similarly related to #18?

**Comment by Cyborger1** [comment]
Oof, I'm a bit rusty on my plugin coding and I'm somewhat busy lately. I could maybe take a look eventually.

**Comment by LlemonDuck** [comment]
Considering the very high demand for this feature, I don't mind revisiting it. However, I won't give any guarantees on how long it will take to implement.

**Comment by dominicfrost** [comment]
I'm thinking about taking a stab at this this weekend. I'm going to add a configuration option that allows the panel to "auto-sync" from the client, so changes to equipment, stance, stats, prayer, etc will auto-populate the panel as they change.

**Comment by dominicfrost** [comment]
Draft PR here: https://github.com/LlemonDuck/dps-calculator/pull/26

**Comment by Violet-Vibes** [comment]
> Draft PR here: #26

Interesting! Cool that you decided to pick it up, how viable is that PR to use atm? (assuming I compile it myself, that is)

**Comment by dominicfrost** [comment]
@Violet-Vibes it should be completely working.

**Comment by Violet-Vibes** [comment]
> 

I'll give it a spin! Could @LlemonDuck maybe have a look and see if this is something that could be merged into main repo and pushed to plugin hub? :)

**Comment by LlemonDuck** [comment]
Discussion about the PR should be placed under the PR instead of here, in case that PR is ultimately not merged as a solution to this issue. I've reviewed and added comments to it now.

Quoting my general response there:
> Overall, this implementation is fine with some changes, but I'm not a fan of the user experience of updating the panel live.
> 
> I've mentioned on what I prefer [here](https://github.com/LlemonDuck/dps-calculator/issues/20#issuecomment-906556071) and as a broader issue in #18.
> 
> Perhaps you'd be interested in working on putting this into a live overlay instead? I think that provides a better UX, similar to the existing Max Hit plugin.

I would urge anyone still interested in this feature to provide me with your feedback on what you would prefer between the side panel being updated with live DPS results, versus having an overlay panel (akin to the following image, but with DPS results) as suggested in #18. The contents could be configured to show the specific results you desire:
![image](https://user-images.githubusercontent.com/1868974/146705702-96acaa19-9af7-4341-9968-793c828ea7e5.png)

I would personally prefer to not need the side panel open for this, and have the overlay panel. However, if others would rather have the side panel update automatically as described initially here, please let me know.

**Comment by LlemonDuck** [comment]
As of 5bb68ab, I added a "Load All From Client", which loads equipment, skills, and prayers in a single home-page action. I expanded this in 1668e55 to include the last-attacked NPC. Finally, in 506466b, I also added a live overlay in-game with your current DPS:
