### ISSUE TITLE
Missing Items from Gear list - Full Torva

### ISSUE THREAD

**Issue by DevKatha** [LlemonDuck/dps-calculator#40]
As Title, Torva is missing from the equipment, unless I am blind. Please add, thank you.

**Comment by LlemonDuck** [comment]
After getting very confused trying to figure out why this was despite multiple wiki data refreshes, it turns out the wiki data had all torva pieces marked as unequipable.

I've fixed the data on the wiki, and once the newest version of the plugin is merged to RL hub, it should pick up the changes automatically.

**Comment by LlemonDuck** [comment]
Closed by runelite/plugin-hub#2446
