### ISSUE TITLE
Nylocas missing

### ISSUE THREAD

**Issue by vikke1234** [LlemonDuck/dps-calculator#45]
Nylocas from tob missing in enemy combat stats.

**Comment by LlemonDuck** [comment]
All raid enemies are missing from the calculator due to a need for raid party size scaling as a parameter in their stats.

ToB should be relatively straightforward once parameterized stats are supported, but CoX scaling formulas are complicated and [unknown](https://twitter.com/JagexAsh/status/1474676283393064965?s=20&t=GE3My3pJGs-FT_M-Ub4q_w)

**Comment by LlemonDuck** [comment]
Added in 06636a99639cb9a6f630f3fa5527100435684012
