### ISSUE TITLE
[Question] Ring of Recoil / Suffering

### ISSUE THREAD

**Issue by Nick2bad4u** [LlemonDuck/dps-calculator#95]
Hello -

I am trying to do some math on whats BiS for Tumeken's Shadow @ KQ.

With max mage and seer's ring (i) I get:

![Max Mage Seer's Ring](https://user-images.githubusercontent.com/20943337/235824603-b0d2f483-652b-4f9d-8a04-a344343053ba.png)

With max mage and Ring of Suffering (ri) I get:

![Max Mage Ring of Suffering](https://user-images.githubusercontent.com/20943337/235824717-d5d1f580-08a8-4a39-bfcf-f4724234274c.png)

I'm wondering how the DPS calc works for calculating Ring of Suffering / Recoil effect?

I'm guessing that there is not any calc for recoil effect because I get the same DPS as picture #2 with no ring slot item at all.

-Typpi

**Comment by brickinthewall4138** [comment]
> I'm guessing that there is not any calc for recoil effect because I get the same DPS as picture https://github.com/LlemonDuck/dps-calculator/issues/2 with no ring slot item at all.

Generally speaking calculating recoil DPS would require calculating monster DPS as a prerequisite which the plugin doesn't do.

For KQ specifically though you can get a ballpark since some of its attacks have 100% accuracy, assuming 
 - its max hit is indeed 31 for all styles 
 - you're standing in melee range to take less damage
 - KQ as wiki states does indeed attack with melee 1/2 the time in melee range, and 1/4 magic/ranged
 - you're protecting from magic / ranged because you're not crazy
 
then it takes an average of 2.09375 recoil damage per successful hit. It attacks every 4 ticks and 1/4 of attacks are nullified by your protection prayer, so the added DPS of a ring of suffering will be between 0.218 and 0.654 depending on its accuracy with melee against you.

So yeah, suffering is going to be better than seers ring no matter what your melee defenses are because 0.218 > 0.055. Hope that helps.

**Comment by Nick2bad4u** [comment]
Thanks for the update and input. Appreciate it.
